#pragma once
#include <fstream>
#include <sstream>
#include <iostream>
#include <filesystem>
#include "../graphics/material/Material.h"
#include "../utils/filePath.h"
namespace Lengine {
    static inline bool loadMTL(const std::string& filepath, Material& mat)
    {
       
        std::ifstream file(filepath);
        if (!file.is_open())
        {
            std::cerr << "Failed to open MTL file: " << filepath << "\n";
            return false;
        }

        std::string line;
        while (std::getline(file, line))
        {
            line = trim(line);

            if (line.empty() || line[0] == '#')
                continue;

            std::istringstream iss(line);
            std::string tag;
            iss >> tag;

            if (tag == "Kd")
                iss >> mat.Kd.r >> mat.Kd.g >> mat.Kd.b;

            else if (tag == "Ka")
                iss >> mat.Ka.r >> mat.Ka.g >> mat.Ka.b;

            else if (tag == "Ks")
                iss >> mat.Ks.r >> mat.Ks.g >> mat.Ks.b;

            else if (tag == "Ke")
                iss >> mat.Ke.r >> mat.Ke.g >> mat.Ke.b;

            else if (tag == "Ns")
                iss >> mat.Ns;

            else if (tag == "d")
                iss >> mat.d;

            else if (tag == "Tr")
                iss >> mat.Tr;

            else if (tag == "Ni")
                iss >> mat.Ni;

            else if (tag == "Tf")
                iss >> mat.Tf;

            else if (tag == "map_Kd")
                iss >> mat.map_Kd_path;

            else if (tag == "map_Ka")
                iss >> mat.map_Ka_path;

            else if (tag == "map_Ks")
                iss >> mat.map_Ks_path;

            else if (tag == "map_Bump" || tag == "bump" || tag == "map_bump")
                iss >> mat.map_bump_path;
        }

        mat.map_Kd = UUID::Null;
        mat.map_Ka = UUID::Null;
        mat.map_Ks = UUID::Null;
        mat.map_bump = UUID::Null;

        return true;
    }

    static void ensureMTLFile(const std::string& filepath)
    {
        namespace fs = std::filesystem;

        fs::path path(filepath);

        if (path.has_parent_path())
            fs::create_directories(path.parent_path());

        if (!fs::exists(path))
        {
            std::ofstream file(filepath);
            file.close(); // creates empty file
        }
    }

    static inline void saveMTL(
        const std::string& filepath,
        const std::string& materialName,
        const Material& mat
    ) {
        ensureMTLFile(filepath);

        std::ofstream file(filepath, std::ios::trunc);
        if (!file.is_open())
        {
            std::cerr << "Failed to write MTL file: " << filepath << "\n";
            return;
        }

        file << "# Generated by Engine\n";
        file << "newmtl " << materialName << "\n\n";

        file << "Ka " << mat.Ka.r << " " << mat.Ka.g << " " << mat.Ka.b << "\n";
        file << "Kd " << mat.Kd.r << " " << mat.Kd.g << " " << mat.Kd.b << "\n";
        file << "Ks " << mat.Ks.r << " " << mat.Ks.g << " " << mat.Ks.b << "\n";

        if (mat.Ke != glm::vec3(0.0f))
            file << "Ke " << mat.Ke.r << " " << mat.Ke.g << " " << mat.Ke.b << "\n";

        file << "Ns " << mat.Ns << "\n";

        if (mat.d < 1.0f)
            file << "d " << mat.d << "\n";

        if (mat.Tr > 0.0f)
            file << "Tr " << mat.Tr << "\n";

        if (mat.Ni != 1.0f)
            file << "Ni " << mat.Ni << "\n";

        if (!mat.map_Ka_path.empty())
            file << "map_Ka " << mat.map_Ka_path << "\n";

        if (!mat.map_Kd_path.empty())
            file << "map_Kd " << mat.map_Kd_path << "\n";

        if (!mat.map_Ks_path.empty())
            file << "map_Ks " << mat.map_Ks_path << "\n";

        if (!mat.map_bump_path.empty())
            file << "map_Bump " << mat.map_bump_path << "\n";

        file.close();
    }

}

